services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: ["/opt/bitnami/scripts/minio/run.sh"]
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    driver:
      local